In [ ]:
import os

In [ ]:
os.chdir("drive/My Drive/Thesis")

FileNotFoundError: ignored

In [ ]:
from gensim.models import Word2Vec
from gensim.models import KeyedVectors

In [ ]:
pre_model = KeyedVectors.load_word2vec_format('w2v/GoogleNews-vectors-negative300.bin', binary=True)

In [ ]:
from gensim.models import FastText

In [ ]:
if 'hello' in pre_model:
  print('Hello')

Hello


In [ ]:
import json
import string

In [ ]:
raw_text = []
raw_label = []
with open('training.json') as f:
  file = json.load(f)
  f.close()
for x in file:
  raw_text.append(x['text'])
  raw_label.append(x['label'])

In [ ]:
import tensorflow as tf

In [ ]:
sequence_length = 100 # tune it to max 300

def wv_input(text_list, label_list):
  input_id_list = []
  attention_mask_list = []
  tag_list = []
  for sentence, stripe in zip(text_list, label_list):
    temp_token = []
    temp_tag = []
    temp_attention = []
    temp_type = []
    for word, tag in zip(sentence.split(), stripe):
      #if tag == 2:
        #tag = 0
      if word in string.punctuation:
        continue
     # print('here')
      if word in pre_model:
        new_token = [pre_model[word]]
        new_label = [tag] 
        new_attention = [1]
      else:
        new_token = [np.array([-1.0 for i in range(300)])]
        new_label = [tag]
        new_attention = [1]
      
      temp_token.extend(new_token)
      temp_tag.extend(new_label)
      temp_attention.extend(new_attention)
   ## print(np.shape(temp_token))
   # print(temp_token)


    if len(temp_token) < sequence_length:
      extend_list = [[-1.00 for i in range(300)]] * (sequence_length - len(temp_token))
      extend_tag = [3] * (sequence_length - len(temp_token))
      temp_attention = temp_attention + [0] * (sequence_length - len(temp_token))
      temp_token = temp_token + extend_list
      temp_tag = temp_tag + extend_tag

    elif len(temp_token) > sequence_length:
      temp_token = temp_token[:sequence_length ]
      temp_attention = temp_attention[:sequence_length]
      temp_tag = temp_tag[:sequence_length]

    input_id_list.append(temp_token)
    attention_mask_list.append(temp_attention)
    tag_list.append(temp_tag)

  
  
  return np.array(input_id_list), np.array(attention_mask_list), np.array(tag_list)

In [ ]:
input_data, mask_data, output_data  = wv_input(raw_text, raw_label)

In [ ]:
import numpy as np

In [ ]:
np.shape(input_data), np.shape(output_data)

((580, 100, 300), (580, 100))

In [ ]:
train_data_x = np.array(input_data[:464])
valid_data_x = np.array(input_data[464:])                   

In [ ]:
train_data_y = np.array(output_data[:464]).reshape(464, 100, 1)
valid_data_y = np.array(output_data[464:]).reshape(116, 100, 1)

In [ ]:
train_mask = np.array(mask_data[:464])
valid_mask = np.array(mask_data[464:])

In [ ]:
from sklearn.metrics import classification_report
from sklearn.metrics import confusion_matrix

In [ ]:
best = 0
batch_count = 0
num_label = 4
def see(ty, tp):
  #model.load('')
  ty = ty.reshape(-1)
  tp = tp.reshape(-1, num_label)
  #print(tp.shape, ty.shape)
  tp = [np.argmax(x) for x in tp]
  dix = np.where(ty == (num_label - 1))[0]
  tp = np.delete(tp, dix)
  ty = np.delete(ty, dix)
  #valid_p = [1 if x > 0.5 else 0 for x in model.predict(valid_x)]
  #valid_p = model.predict(valid_x)
 # print(np.shape(tp), ty.shape)
  print('\nClassification Report \n\n')
  
  f = classification_report(ty, tp)
  print(f)
 # print('\nPrint Confusion Matrix \n\n')
  print(confusion_matrix(ty, tp))
  return f1_score(ty, tp, average=None)[1]

In [ ]:
class mcb(tf.keras.callbacks.Callback):
  def on_epoch_end(self, epoch, log=None):
   # global train_x, train_y, valid_x, valid_y
    print('here')
    _y = self.model.predict(train_data_x)
    see(train_data_y, _y)
    _y = self.model.predict(valid_data_x)
    see(valid_data_y, _y)

In [ ]:
model = tf.keras.Sequential([
                             tf.keras.layers.LSTM(units=512, return_sequences=True),
                             tf.keras.layers.LSTM(units=128, return_sequences=True),
                             tf.keras.layers.TimeDistributed(tf.keras.layers.Dense(64, activation='relu')),
                             tf.keras.layers.Dense(1024, activation='relu'),
                             tf.keras.layers.Dense(4, activation='softmax')
])

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam',
              metrics=['accuracy'])

In [ ]:
model.fit(train_data_x, train_data_y, epochs=3,
          validation_data=(valid_data_x, valid_data_y),
          sample_weight=train_mask, callbacks=[mcb()],
          batch_size=8)

Epoch 1/3
58/58 [==============================] - 61s 1s/step - loss: 0.3615 - accuracy: 0.2872 - val_loss: 3.7179 - val_accuracy: 0.2997
here
(46400, 4) (46400,)
(46400,) (46400,)

Classification Report 


              precision    recall  f1-score   support

           0       0.72      0.94      0.82     13690
           1       0.00      0.00      0.00      3170
           2       0.03      0.35      0.06      2716
           3       0.00      0.00      0.00     26824

    accuracy                           0.30     46400
   macro avg       0.19      0.32      0.22     46400
weighted avg       0.22      0.30      0.25     46400


Print Confusion Matrix 




/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1272: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


[[12900     0   790     0]
 [ 2984     0   186     0]
 [ 1774     0   942     0]
 [  168     0 26656     0]]
(11600, 4) (11600,)
(11600,) (11600,)

Classification Report 


              precision    recall  f1-score   support

           0       0.69      0.94      0.80      3417
           1       0.00      0.00      0.00       929
           2       0.04      0.33      0.07       795
           3       0.00      0.00      0.00      6459

    accuracy                           0.30     11600
   macro avg       0.18      0.32      0.22     11600
weighted avg       0.21      0.30      0.24     11600


Print Confusion Matrix 


[[3213    0  204    0]
 [ 867    0   62    0]
 [ 531    0  264    0]
 [  45    0 6414    0]]
Epoch 2/3
58/58 [==============================] - 54s 930ms/step - loss: 0.2622 - accuracy: 0.2987 - val_loss: 4.1987 - val_accuracy: 0.3279
here
(46400, 4) (46400,)
(46400,) (46400,)

Classification Report 


              precision    recall  f1-score   support

      